server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: systemJson
  static_configs:
  - targets:
      - localhost
    labels:
      job: logs
      __path__: /home/tages/tmp/lesson1/test.log

  pipeline_stages:
    - json:
        expressions:
          level: 
          namespace:    
    - labels:
        level:
        namespace:
    - match:
        selector: '{level=~"info.*"}'
        stages:
          - tenant:
              value: test1
    - match:
        selector: '{level=~"boom"}'
        stages:
          - tenant:
              value: test2
    - match:
        selector: '{namespace=~"tn-finapp.*"}'
        stages:
          - tenant:
              value: tn-finapp                    

